package org.jmc.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * @author adrian.
 */
public class FAQPanel {
	private JPanel faqPanel;
	private JLabel title;
	private JScrollPane scroll;
	private JPanel questions;

	FAQPanel() {
		$$$setupUI$$$();
		init();
	}

	private void init() {

		title.setFont(new Font(CustomFont.minecraft.getName(), Font.PLAIN, 25));

		questions.setBackground(CustomPalette.BACK_GROUND);
		questions.setForeground(CustomPalette.FORE_GROUND);

		scroll.getVerticalScrollBar().setUI(new CustomScrollBar());
		scroll.getVerticalScrollBar().setUnitIncrement(12);
		scroll.setBorder(null);

		questions.setLayout(new BoxLayout(questions, BoxLayout.Y_AXIS));

		for (int i = ContentUtil.CONTENT_FAQ.length - 1; i >= 0; i--) {
			JTextArea answer = new JTextArea(ContentUtil.CONTENT_FAQ[i]);
			answer.setEditable(false);
			answer.setLineWrap(true);
			answer.setWrapStyleWord(true);
			answer.setBackground(CustomPalette.BACK_GROUND);
			answer.setForeground(CustomPalette.FORE_GROUND);
			answer.setFont(new Font(CustomFont.minecraft.getName(), Font.PLAIN, 16));
			answer.setAlignmentX(Component.LEFT_ALIGNMENT);

			JTextArea question = new JTextArea(ContentUtil.CONTENT_FAQ[--i]);
			question.setEditable(false);
			question.setLineWrap(true);
			question.setWrapStyleWord(true);
			question.setBackground(CustomPalette.BACK_GROUND);
			question.setFont(new Font(CustomFont.minecraft.getName(), Font.PLAIN, 20));
			question.setForeground(CustomPalette.FLASHY_GREEN);
			question.setBorder(BorderFactory.createEmptyBorder(40, 0, 10, 0));
			question.setAlignmentX(Component.LEFT_ALIGNMENT);

			questions.add(answer, 0);
			questions.add(question, 0);
		}
	}

	public JPanel getPanel() {
		return faqPanel;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		faqPanel = new JPanel();
		faqPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		title = new JLabel();
		title.setFont(new Font(title.getFont().getName(), title.getFont().getStyle(), title.getFont().getSize()));
		title.setHorizontalAlignment(0);
		title.setHorizontalTextPosition(0);
		title.setText("FAQ");
		faqPanel.add(title, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		scroll = new JScrollPane();
		scroll.setHorizontalScrollBarPolicy(31);
		faqPanel.add(scroll, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(900, -1), null, 0, false));
		questions = new JPanel();
		questions.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		scroll.setViewportView(questions);
		questions.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25), null));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return faqPanel;
	}
}
